services:
  api:
    container_name: clean_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password123@db:3306/clean_todo 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  db:
    container_name: clean_api
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password123 
      - MYSQL_DATABASE=clean_todo      
      - MYSQL_USER=root           
    volumes:
      - mysql_data:/var/lib/mysql   
    ports:
      - "3306:3306"                 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    restart: unless-stopped

volumes:
  mysql_data: